FROM nginx:alpine

# Copiar o arquivo HTML para o diretório de conteúdo do nginx
COPY static-grid.html /usr/share/nginx/html/index.html

# Expor a porta 80
EXPOSE 80

# Comando padrão do nginx já está configurado

